name: Ben Renschen
favicon: null
layout_spectrum: 0.30026186257600784
typography_spectrum: 0.5441316517535597
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.7179772555828094
  lightness: 0.1812843147199601
  saturation: 0.5752184800803661
  rhythmicContrast: 0.09647809783928096
purpose: []
